# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# Cursor
cursor {
    no_hardware_cursors = false
    default_monitor = DP-2
}
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`

# Primary monitor: workspace 1 starts on the big MSI (DP-2)
workspace = 1, monitor:DP-2, default:true
