# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# Cursor
cursor {
    no_hardware_cursors = false
    default_monitor = eDP-1
}
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,24

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`
